### ISSUE TITLE
Create basic application database

### ISSUE THREAD

**Issue by dominguesgm** [DominguesGM/feup-ltw#5]
Details of the database according to the project description.

**Comment by dominguesgm** [comment]
Atenção: há duas relações entre utilizador e evento: Owner e SignedUp(inscrito)

**Comment by pmpontes** [comment]
I'm taking that into account.

**Comment by pmpontes** [comment]
Almost complete - further testing required.

**Comment by pmpontes** [comment]
Agreed changes performed.
